#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
import subprocess
import re
import time


class Cores(object):
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'

    BHEADER = '\033[1;95m'
    BOKBLUE = '\033[1;94m'
    BOKGREEN = '\033[1;92m'
    BWARNING = '\033[1;93m'
    BFAIL = '\033[1;91m'

SEPARADOR_DE_LINHA = "------------------------------- {} ----------------------------------{}"


def extrai_duracao(info):
    padrao_re = re.compile(r"[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{2}")
    partes = padrao_re.findall(info)
    if partes:
        duracao = partes[0].split(":")
        hora = int(duracao[0])
        minuto = int(duracao[1])
        segundo = float(duracao[2])
        return float(hora * 3600) + float(minuto * 60) + segundo, partes[0]


def formata_tempo(segundos):
    hora = 0
    if segundos >= 3600:
        hora = int(segundos / 3600)
    segundos -= (hora * 3600)
    minutos = int(segundos / 60)
    segundos -= (minutos * 60)
    return "{:02d}:{:02d}:{:02d}".format(hora, minutos, segundos)


if __name__ == "__main__":
    args = sys.argv[1:]
    if not args:
        actual_dir = os.getcwd()
    else:
        actual_dir = args[0]
    mp3_files = [mp3_file for mp3_file in os.listdir(actual_dir) if mp3_file.endswith(".mp3")]
    mp3_files.sort()
    for mp3_file in mp3_files:
        proc_info = subprocess.check_output(['omxplayer', '-i', '{}/{}'.format(actual_dir, mp3_file)], stderr=subprocess.STDOUT)
        _duracao = extrai_duracao(proc_info)
        print "Tocando {}. Duracao: {}".format(mp3_file, _duracao[1])
        play = subprocess.Popen(['omxplayer', '-s', '{}/{}'.format(actual_dir, mp3_file)], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        tempo = int(_duracao[0])
        while tempo > 0:
            sys.stdout.write(u"Duração: {}   \r".format(formata_tempo(tempo)))
            sys.stdout.flush()
            tempo -= 1
            time.sleep(1)
        play.terminate()
        os.system("killall omxplayer.bin")
        print "{} terminou\n\n".format(mp3_file)
